# Generated by Django 5.0.6 on 2024-06-04 03:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='person_images'),
        ),
    ]
