# Generated by Django 5.0.6 on 2024-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_personalimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_media',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
